import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Icon from '../components/svg/icon'
import { hideSvg } from './script/main'

export default function Home({listMusic}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.global}>
          {listMusic.map((listMusic, index) => (
            <div key={index} id={`bigBox${index}`} className={styles.subGlobal} onClick={() => hideSvg(index)}>
              <div className={styles.icon}><Icon/></div> <div>{listMusic.name}</div>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:3000/api/hello`, {
      headers: { Accept: "application/json" },
  })
  const listMusic = await res.json()
  return{props:{listMusic}}
}